In [1]:
import gurobipy as gp
from gurobipy import GRB
import pandas as pd
from numpy import genfromtxt
import numpy as np
rt = genfromtxt(r"C:\Users\ricky\Downloads\ZJX_West.csv", delimiter=',')
#rt.rename(columns={'1': 'data'}, inplace=True)
#rt2 = list(rt.data)
print(rt)

[1. 1. 1. ... 1. 1. 1.]


In [2]:
T = 1344 #total number of time periods
tpmins= 15 #total length of each time period in minutes
shift = [8, 10] #regular and compressed shift lengths

indices = range(1, len(rt)+1)
indices2 = range(1, len(shift)+1)
print(indices)
print(indices2)

range(1, 1345)
range(1, 3)


In [3]:
tau_1 = np.array([max(1, t - 60 * shift[0] /15 + 1) for t in range (1, T +1)])
#tau_1[tau_1 < 0] = 0
tau_2 = np.array([max(1, t - 60 * shift[1] /15 + 1) for t in range (1, T +1)])
print(tau_1)
print(tau_2)

[1.000e+00 1.000e+00 1.000e+00 ... 1.311e+03 1.312e+03 1.313e+03]
[1.000e+00 1.000e+00 1.000e+00 ... 1.303e+03 1.304e+03 1.305e+03]


In [8]:
try:
    
    m = gp.Model("Shift Distribution Problem")
    
    #vector of variables
    x = {}
    #x[i, j] = m.addVars(indices, indices2, lb=0.0, vtype = GRB.BINARY, name='binary')
    x = m.addVars(indices, indices2, lb=0.0, vtype = GRB.BINARY, name='binary')

    #set objective
    m.setObjective(gp.quicksum([x[i, j] for i in indices for j in indices2]), GRB.MINIMIZE)
    
    #adding constraints
    #for i in indices:
        #for j in indices2:
           # m.addConstr(gp.quicksum(x[i, j] for i in indices >= rt[j]))
            
    m.addConstrs(gp.quicksum(x[i, j] for  in indices2) >= rt[i] for i in indices)
            
    #m.addConstr(x[i, j] == 0)
    #m.addConstr(x[i, j] == 1)
    
    m.write('Shift Distribution Problem.lp')
    m.optimize()
    
    #output
    if m.status == GRB.OPTIMAL:
        for v in m.getVars():
            print('%s %g' % (v.varName, v.x))
            print('Obj: %g' % m.objVal)
    elif m.status == GRB.INFEASIBLE:
        print('LP is infeasible.')
    elif m.status == GRB.UNBOUNDED:
        print('LP is unbounded.')
except gp.GurobiError as e:
        print('Error code ' + str(e.errno) + ": " + str(e))
except AttributeError:
        print('Encountered an attribute error')

IndexError: index 1344 is out of bounds for axis 0 with size 1344

In [5]:
m.write('Shift Distribution Problem.lp')

In [6]:
len(x)

2688

In [42]:
len(indices2)

1

In [43]:
indices2

range(1, 2)